name: CMake

on:
  push:
  workflow_dispatch:


jobs:
  build_and_release:
    strategy:
        fail-fast: false
        matrix:
          # os: [ubuntu-latest, ubuntu-18.04]
          os : [ubuntu-20.04]
          compiler: [gcc]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo bash scripts/install_ci.sh
        
      
    - name: Format
      run: ./run-clang-format/run-clang-format.py -r --clang-format-executable clang-format-11 modules sources stress test third_party
    
    - name: Test
      env:
        CC: ${{ matrix.compiler }}
        CC_FOR_BUILD: ${{ matrix.compiler }}
      run: make run_test
